function tsvTable = importTSVProtocol(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TSVTABLE = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  TSVTABLE = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  tsvTable = importfile("/home/alexandresayal/media-sim01/DATAPOOL/VPMB/VPMB-BIDS-NLREG/sub-01/func/sub-01_task-AA_acq-0500_run-01_events.tsv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Nov-2021 12:03:00

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["onset", "duration", "trial_type"];
opts.VariableTypes = ["double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "trial_type", "EmptyFieldRule", "auto");

% Import the data
tsvTable = readtable(filename, opts);

end