function LocalizerROISelection20221014 = importROIcsv(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LOCALIZERROISELECTION20221014 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  LOCALIZERROISELECTION20221014 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  LocalizerROISelection20221014 = importfile("/DATAPOOL/home/alexandresayal/GitRepos/vpmb/Module5-SPM12/Localizer_ROISelection_20221014.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Oct-2022 17:38:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ROIname", "EPI_X", "EPI_Y", "EPI_Z", "EPI_peakT", "GRE_X", "GRE_Y", "GRE_Z", "GRE_peakT", "SPE_X", "SPE_Y", "SPE_Z", "SPE_peakT", "NLREG_X", "NLREG_Y", "NLREG_Z", "NLREG_peakT", "NONE_X", "NONE_Y", "NONE_Z", "NONE_peakT"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "ROIname", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "ROIname", "EmptyFieldRule", "auto");

% Import the data
LocalizerROISelection20221014 = readtable(filename, opts);

end